Getting Distance from Distance Getter
cachemoney8096/2024-crescendo pull request #36
Opened 2024-02-17 20:03 UTC by itsmesp8343

-Flag to tell whether using distance getter or not -methods to get distance and change boolean
-added to periodic
-changed in prep score how to get distance

2024-02-17 21:52 UTC, allison324 approved these changes

2024-02-17 21:52 UTC, tails618 approved these changes
Lgtm! Remember to format

2024-02-18 00:33 UTC, balghane commented on src/main/java/frc/robot/commands/SpeakerPrepScoreSequence.java
> +        new InstantCommand(() -> shooter.setShooterDistance(shooter.getDistanceFromDistanceGetter())),
Replace this with something that sets `distGetBool` to true?

2024-02-18 00:33 UTC, balghane commented on src/main/java/frc/robot/commands/SpeakerPrepScoreSequence.java
> +        new InstantCommand(() -> shooter.setDistanceGetterOff()));
Maybe let's only turn it off after we shoot, not at the end of prep

2024-02-18 00:33 UTC, balghane commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +  private Boolean distGetBool;
Can you add a `/** */` style comment about what this results in?

2024-02-18 00:35 UTC, balghane requested changes
see comments

2024-02-23 00:22 UTC, itsmesp8343 commented
/format

2024-03-20 20:41 UTC, closed without merging